name: ruangkita_app1
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.3 # versi terkini mungkin berbeda
  sqlite3: ^2.5.0
  sqflite_common_ffi: ^2.2.3
  sqflite_common_ffi_web: '^0.4.5+4'
  path: ^1.8.3
  http: ^1.2.2
  bcrypt: ^1.1.3
  provider: ^6.0.5
  shared_preferences: ^2.0.15

  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/logo/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Gotham
      fonts:
        - asset: assets/fonts/Gotham-Black.otf
        - asset: assets/fonts/Gotham-Bold.otf
        - asset: assets/fonts/GothamBold.ttf
        - asset: assets/fonts/GothamBoldItalic.ttf
        - asset: assets/fonts/GothamBook.ttf
        - asset: assets/fonts/Gotham-BookItalic.otf
        - asset: assets/fonts/GothamBookItalic.ttf
        - asset: assets/fonts/Gotham-Light.otf
        - asset: assets/fonts/GothamLight.ttf
        - asset: assets/fonts/GothamLightItalic.ttf
        - asset: assets/fonts/GothamMedium.ttf
        - asset: assets/fonts/GothamMedium_1.ttf
        - asset: assets/fonts/GothamMediumItalic.ttf
        - asset: assets/fonts/Gotham-Thin.otf
        - asset: assets/fonts/Gotham-ThinItalic.otf
        - asset: assets/fonts/Gotham-UltraItalic.otf
        - asset: assets/fonts/Gotham-XLight.otf
        - asset: assets/fonts/Gotham-XLightItalic.otf

flutter_native_splash:
  color: "#2280BF" 
  image: assets/logo/RuangKitaLogo.png  
  android: true
  ios: true
  web: false  
